# flake8: noqa: B950
# fmt: off
# This file was generated by AutoHeuristic. Do not modify it manually!
# To regenerate this file, take a look at the steps in the README.md file inside torchgen/_autoheuristic/pad_mm/
from typing import Optional

from torch._inductor.autoheuristic.autoheuristic_utils import (
    AHContext,
    AHMetadata,
    Choice,
)
from torch._inductor.autoheuristic.learnedheuristic_interface import (
    LearnedHeuristicDecision,
)


class PadMMA100(LearnedHeuristicDecision):

    def __init__(self) -> None:
        self.choices: list[Choice] = []
        self.fill_choices()

    def check_precondition(self, metadata: AHMetadata, context: AHContext,) -> bool:
        return (
            metadata.name == self.get_name()
            and metadata.shared_memory == 166912
            and str(metadata.device_capa) == "(8, 0)"
        )

    def get_confidence_threshold(self) -> float:
        return 0.0

    def get_choice(self, idx: int) -> Optional[str]:
        if idx < len(self.choices):
            return self.choices[idx]
        return None

    def fill_choices(self) -> None:
        self.choices.append('orig')
        self.choices.append('pad')

    def get_name(self) -> str:
        return 'pad_mm'

    def get_best_choices(self, context: AHContext) -> Optional[list[tuple[float, int]]]:
        if str(context.get_value('mat1_innermost_needs_padding')) != 'False':
            if context.get_value('arith_intensity') <= 880.0238037109375:
                if str(context.get_value('m_multiple_2')) != 'True':
                    if context.get_value('n') <= 652.0:
                        if context.get_value('m') <= 4341.0:
                            return [(0.780, 0), (0.220, 1)]
                        else:
                            return [(1.000, 0)]
                    else:
                        if context.get_value('m*k') <= 107278336.0:
                            return [(0.845, 1), (0.155, 0)]
                        else:
                            return [(0.565, 0), (0.435, 1)]
                else:
                    if context.get_value('mat2_stride_0') <= 2432.0:
                        if str(context.get_value('k_multiple_2')) != 'True':
                            return [(0.517, 1), (0.483, 0)]
                        else:
                            return [(0.911, 0), (0.089, 1)]
                    else:
                        if str(context.get_value('using_tf32')) != 'False':
                            return [(0.806, 1), (0.194, 0)]
                        else:
                            return [(0.884, 0), (0.116, 1)]
            else:
                if context.get_value('n') <= 2640.0:
                    if context.get_value('m_padded_length') <= 1.5:
                        if context.get_value('mat1_stride_0') <= 6227.5:
                            return [(0.996, 1), (0.004, 0)]
                        else:
                            return [(0.940, 1), (0.060, 0)]
                    else:
                        if str(context.get_value('m_multiple_2')) != 'True':
                            return [(1.000, 1)]
                        else:
                            return [(0.797, 0), (0.203, 1)]
                else:
                    if context.get_value('m*k') <= 404182016.0:
                        if str(context.get_value('mat2_innermost_needs_padding')) != 'False':
                            return [(0.879, 1), (0.121, 0)]
                        else:
                            return [(0.995, 1), (0.005, 0)]
                    else:
                        return [(0.725, 1), (0.275, 0)]
        else:
            if context.get_value('n_padded_length') <= 0.5:
                if str(context.get_value('mat2_innermost_needs_padding')) != 'False':
                    if str(context.get_value('k_multiple_2')) != 'True':
                        return [(0.506, 1), (0.494, 0)]
                    else:
                        return [(0.985, 0), (0.015, 1)]
                else:
                    if str(context.get_value('using_tf32')) != 'False':
                        if context.get_value('m*k') <= 93734912.0:
                            return [(0.981, 0), (0.019, 1)]
                        else:
                            return [(0.996, 0), (0.004, 1)]
                    else:
                        if str(context.get_value('prepadded_mat1')) != 'True':
                            return [(0.950, 0), (0.050, 1)]
                        else:
                            return [(0.750, 0), (0.250, 1)]
            else:
                if str(context.get_value('using_tf32')) != 'False':
                    if str(context.get_value('n_multiple_2')) != 'False':
                        if context.get_value('m') <= 2024.0:
                            return [(0.748, 0), (0.252, 1)]
                        else:
                            return [(0.886, 1), (0.114, 0)]
                    else:
                        if str(context.get_value('mat2_innermost_needs_padding')) != 'True':
                            return [(0.825, 1), (0.175, 0)]
                        else:
                            return [(0.991, 1), (0.009, 0)]
                else:
                    return [(0.957, 0), (0.043, 1)]
